


all:
	python3 setup.py build_ext --inplace

clean:
	rm -rf build
	rm -rf *.so
	rm -rf *.c
	rm -rf *.pyc
	rm -rf *.pyo
	rm -rf *.pyd
	rm -rf *.html
	rm -rf *.so.dSYM
	rm -rf *.egg-info
	rm -rf __pycache__
	rm -rf .pytest_cache
	rm -rf .coverage
	rm -rf .cache
	rm -rf .mypy_cache
	rm -rf .tox
	rm -rf .eggs
	rm -rf .hypothesis

.phoney: clean